# Usage: KITCHEN_YAML=.kitchen.docker.yml bundle exec kitchen list
---
settings:
  parallel: true

transport:
  name: dokken

provisioner:
  name: dokken
  data_path: test/shared

verifier:
  root_path: '/opt/verifier'
  sudo: false

driver:
  name: dokken

platforms:
- name: centos-7
  driver:
    image: centos:7
    platform: rhel
    run_command: /usr/lib/systemd/systemd
    provision_command:
      - /bin/yum update -y
      - /bin/yum install -y initscripts net-tools wget
- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    platform: ubuntu
    disable_upstart: false
    run_command: /sbin/init
    provision_command:
      - /usr/bin/apt-get update
      - /usr/bin/apt-get install apt-transport-https net-tools -y

suites:
- name: default
  run_list:
    - recipe[selenium_test::package]
    - recipe[selenium_test::hub]
    - recipe[selenium_test::node]
