# Usage: KITCHEN_YAML=.kitchen.macosx.yml kitchen list
---
driver:
  name: vagrant
  provider: vmware_fusion
  customize:
    memory: 2048

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.16

platforms:
  - name: macosx-10.10
    driver:
      box: macosx-10.10
    driver_config:
      network:
      - ["forwarded_port", {guest: 4444, host: 4447}]

suites:
  - name: default
    run_list:
      - recipe[java_se]
      - recipe[selenium_grid_test::package]
      - recipe[selenium_grid::hub]
      - recipe[selenium_grid::node]
    attributes:
      selenium_grid:
        username: vagrant
        password: vagrant
        chrome:
          max_instances: 5
        firefox:
          max_instances: 5
        htmlunit:
          max_instances: 1
        ie:
          max_instances: 1
        opera:
          max_instances: 5
        phantomjs:
          max_instances: 5
        safari:
          max_instances: 1
