---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.18

platforms:
  - name: windows-2012r2
    driver:
      box: dhoer/windows-2012r2
    attributes:
      mozilla_firefox:
        version: latest # latest-esr doesn't have 64bit version
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.7
  - name: centos-7.1
  - name: debian-7.8
  - name: debian-8.1

suites:
  - name: default
    run_list:
      - recipe[mozilla_firefox_test::default]
      - recipe[mozilla_firefox_test::version]
      - recipe[mozilla_firefox_test::x11]
    attributes:

  - name: windows_32bit_only
    run_list:
      - recipe[mozilla_firefox_test::default]
      - recipe[mozilla_firefox_test::version]
    attributes:
      mozilla_firefox:
        32bit_only: true
    excludes:
     - ubuntu-12.04
     - ubuntu-14.04
     - centos-6.7
     - centos-7.1
     - debian-7.8
     - debian-8.1
